platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -pre -y
  - cinst gitlink -Pre -y

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - NuGet restore Source/OxyPlot.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.AppVeyor.sln
  verbosity: minimal

after_build:
  - gitlink c:\projects\oxyplot-contrib -u https://github.com/oxyplot/oxyplot-contrib -f Source/OxyPlot.AppVeyor.sln 
  - NuGet pack Source\OxyPlot.Contrib\OxyPlot.Contrib.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Source\OxyPlot.Contrib\bin\Release
    name: OxyPlot-Contrib-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/  
