image: Visual Studio 2019
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -y

before_build:
  - nuget restore Source/OxyPlot.Contrib.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.Contrib.sln
  verbosity: minimal

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/oxyplot/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
